AppElevator/urls.py
from django.urls import path
from .views import editar_perfil, agregar_avatar, register, logout_view
from .views import proyecto_view, productora_view, autor_view, productor_view
from .views import lista_proyecto, lista_productor, lista_productora, lista_autor
from .views import inicio, vista_proyecto, vista_productor, vista_productora, vista_autor
from .views import formulario_proyecto,formulario_autores, formulario_productores, formulario_productoras
from .views import proyecto_detalles, productor_detalles, productora_detalles,autor_detalles
from .views import editar_proyecto, eliminar_proyecto, editar_autor, eliminar_autor
from .views import editar_productor, eliminar_productor, editar_productora, eliminar_productora
from django.contrib.auth.views import LogoutView
from .views import login_view

app_name = 'AppElevator'
urlpatterns = [
    path('agregar-proyecto/<nombre>/<logline>/<plot>/<genero>/',proyecto_view),
    path('agregar-productora/<nombre>/<pag_web>/<email>/<pais>/',productora_view),
    path('agregar-autor/<nombre>/<apellido>/<int:edad>/<email>/<pais>/',autor_view),
    path('agregar-productor/<nombre>/<apellido>/<int:edad>/<email>/<pais>/',productor_view),
    
    # LISTAS 

    path('lista-productor/',lista_productor, name='lista_productor'),
    path('lista-proyecto/', lista_proyecto, name='lista_proyecto'),
    path('lista-productora/',lista_productora, name='lista_productora'),
    path('lista-autor/',lista_autor, name='lista_autor'),
    path('', inicio),
    
    # VISTAS
    path('vista-autor/',vista_autor),
    path('vista-productor/',vista_productor),
    path('vista-productora/',vista_productora),
    path('vista-proyecto/',vista_proyecto),
    
    # PRODUCTORES
    path('productor-detalles/<nombre>/', productor_detalles),

    path('formulario-productores/',formulario_productores, name= 'formularioProductores'),
    path('editar-productor/<nombre>/', editar_productor, name='editarProductor'),
    path('eliminar-productor/<nombre>/', eliminar_productor, name='eliminarProductor'),

    # PRODUCTORA AUDIOVISUAL
    path('productora-detalles/<nombre>/', productora_detalles),
    path('formulario-productoras/',formulario_productoras, name= 'formularioProductoras'),
    path('editar-productora/<nombre>/', editar_productora, name='editarProductora'),
    path('eliminar-productora/<nombre>/', eliminar_productora, name='eliminarProductora'),
    
    # PROYECTO
    path('proyecto-detalles/<nombre>/', proyecto_detalles),
    path('formulario-proyecto/',formulario_proyecto, name= 'formularioProyecto'),
    path('editar-proyecto/<nombre>/', editar_proyecto, name='editarProyecto'),
    path('eliminar-proyecto/<nombre>/', eliminar_proyecto, name='eliminarProyecto'),
    
    # AUTOR
    path('autor-detalles/<nombre>/', autor_detalles),
    path('formulario-autores/',formulario_autores, name= 'formularioAutores'),
    path('editar-autor/<nombre>/', editar_autor, name='editarAutor'),
    path('eliminar-autor/<nombre>/', eliminar_autor, name='eliminarAutor'),
    
    # REGISTRO
    path('login/', login_view, name='Login'),
    path('registrar/', register, name="Registrar"),
    path('logout/', logout_view, name='Logout'),
    path('editar-perfil/', editar_perfil, name="EditarPerfil"),

    # AVATAR
    path('agregar-avatar/', agregar_avatar, name="AgregarAvatar"),

    
]

ProyectoElevatorPitch/urls.py
from django.contrib import admin
from django.urls import path , include



urlpatterns = [
    path('App-Elevator/', include('AppElevator.urls')),
    path('admin/', admin.site.urls),
]

AppElevator/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import User

# Create your models here.



# Modelo que representa a un Autor.

class Autor(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=50)
    edad = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    email = models.EmailField(max_length=254)
    pais = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"
    
 
# Modelo que representa a un Productor.

class Productor (models.Model):
    nombre = models.CharField(max_length=30)
    apellido =  models.CharField(max_length=50)
    edad = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    email = models.EmailField(max_length=254)
    pais = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"
    
# Modelo que representa a una Productora audiovisual

class Productora_audiovisual (models.Model):
    nombre = models.CharField(max_length=30)
    pag_web =  models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    pais = models.CharField(max_length=50)
    Productor =models.ManyToManyField (Productor)

    def __str__(self):
        return self.nombre
    
# Modelo que representa a un Proyecto.

class Proyecto(models.Model):
    nombre = models.CharField(max_length=50)
    logline = models.CharField(max_length=1000)
    plot = models.CharField(max_length=5000)
    genero = models.CharField(max_length=50)
    Autor = models.ForeignKey(Autor, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.nombre
    
class Avatar(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', blank=True, null=True)

AppElevator/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from .models import Autor, Productor, Productora_audiovisual, Proyecto
from .models import Avatar

class ProyectoForm(forms.ModelForm):
    class Meta:
        model = Proyecto
        fields = ['nombre', 'logline', 'plot', 'genero', 'Autor']

class ProductoraForm(forms.ModelForm):
    class Meta:
        model = Productora_audiovisual
        fields = ['nombre', 'pag_web', 'email', 'pais', 'Productor']

class AutorForm(forms.ModelForm):
    class Meta:
        model = Autor
        fields = ['nombre', 'apellido', 'edad', 'email', 'pais']

class ProductorForm(forms.ModelForm):
    class Meta:
        model = Productor
        fields = ['nombre', 'apellido', 'edad', 'email', 'pais']

class UserEditForm (UserChangeForm):

    password = forms.CharField(
        help_text="",
        widget=forms.HiddenInput(), required=False
    )

    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repita contraseña", widget=forms.PasswordInput)

    class Meta:
        model=User
        fields=('email', 'first_name', 'last_name', 'password1', 'password2')

    def clean_password2(self):

        print(self.cleaned_data)

        password2 = self.cleaned_data["password2"]
        if password2 != self.cleaned_data["password1"]:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return password2
    
class AvatarFormulario(forms.ModelForm):

    class Meta:
        model=Avatar
        fields=('imagen',)

AppElevator/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Avatar
from django.contrib import messages

from .forms import (
    ProyectoForm, AutorForm, ProductorForm, ProductoraForm,
    UserEditForm, AvatarFormulario
)
from .models import Proyecto, Productora_audiovisual, Autor, Productor, Avatar
from django.contrib import messages


# Base de datos
def proyecto_view(request, nombre, logline, plot, genero):
    proyecto = Proyecto(nombre=nombre, logline=logline, plot=plot, genero=genero)
    proyecto.save()

    return HttpResponse(f"""
<p> Proyecto: {proyecto.nombre}, logline {proyecto.logline}, plot {proyecto.plot}, genero {proyecto.genero} Agregado con Exito!</p>""")

def productora_view(request, nombre, pag_web, email, pais):
    productora = Productora_audiovisual (nombre=nombre, pag_web=pag_web, email=email, pais=pais)
    productora.save()

    return HttpResponse(f"""
<p> productora: {Productora_audiovisual.nombre}, pag_web {Productora_audiovisual.pag_web}, email {Productora_audiovisual.email}, pais {Productora_audiovisual.pais} Agregado con Exito!</p>""")

def autor_view(request, nombre, apellido, edad, email, pais):
    autor = Autor(nombre=nombre, apellido=apellido, edad=edad, email=email, pais=pais)
    autor.save()

    return HttpResponse(f"""
<p> autor: {Autor.nombre} {Autor.apellido}, edad {Autor.edad}, email {Autor.email}, pais {Autor.pais} Agregado con Exito!</p>""")

def productor_view(request, nombre, apellido, edad, email, pais):
    productor = Productor(nombre=nombre, apellido=apellido, edad=edad, email=email, pais=pais)
    productor.save()

    return HttpResponse(f"""
<p> Productor: {Productor.nombre} {Productor.apellido}, edad {Productor.edad}, email {Productor.email}, pais {Productor.pais} Agregado con Exito!</p>""")

# Listas

def lista_proyecto(request):
    listas_proyecto = Proyecto.objects.all().order_by('nombre')

    paginator = Paginator(listas_proyecto, 5) 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'listas_proyecto.html', {"listas_proyecto": page_obj})

def lista_productor(request):
    listas_productor = Productor.objects.all().order_by('nombre')

    paginator = Paginator(listas_productor, 3) # Muestra 3 productores por página
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'listas_productor.html', {"listas_productor": page_obj})



def lista_productora(request):
    listas_productora = Productora_audiovisual.objects.all().order_by('nombre')

    paginator = Paginator(listas_productora, 3) # Muestra 3 productoras por página
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'listas_productora.html', {"listas_productora": page_obj})

def lista_autor(request):
    listas_autor = Autor.objects.all().order_by('nombre')

    paginator = Paginator(listas_autor, 3) # Muestra 3 autores por página
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'listas_autor.html', {"listas_autor": page_obj})


#Vistas

def inicio (request):
    return render (request,'inicio.html')

def vista_autor (request):
    return render (request,'listas_autor.html')

def vista_productor (request):
    return render (request,'listas_productor.html')

def vista_productora (request):
    return render (request, 'listas_productora.html')

def vista_proyecto (request):
    return render (request,'listas_proyecto.html')

#Formularios

def formulario_proyecto(request):
    if request.method == 'POST':
        form = ProyectoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('AppElevator:lista_proyecto')
    else:
        form = ProyectoForm()

    return render(request, 'formulario_proyecto.html', {'form': form})

def formulario_autores(request):
    if request.method == 'POST':
        form = AutorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('AppElevator:lista_autor')
    else:
        form = AutorForm()

    return render(request, 'formulario_autores.html', {'form': form})

def formulario_productores(request):
    if request.method == 'POST':
        form = ProductorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('AppElevator:lista_productor')
    else:
        form = ProductorForm()

    return render(request, 'formularioProductores.html', {'form': form})

def formulario_productoras(request):
    if request.method == 'POST':
        form = ProductoraForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('AppElevator:lista_productora')
    else:
        form = ProductoraForm()

    return render(request, 'formularioProductoras.html', {'form': form})

# Editar Eliminar Proyecto y Html details
def proyecto_detalles(request, nombre):
    encontrarProyectoPorNombre = Proyecto(nombre=nombre)

    proyecto = get_object_or_404(Proyecto, nombre=encontrarProyectoPorNombre.nombre)
    return render(request, 'proyecto_detalles.html', {'proyecto': proyecto})

def editar_proyecto(request, nombre):
    proyecto = get_object_or_404(Proyecto, nombre=nombre)

    if request.method == 'POST':
        form = ProyectoForm(request.POST, instance=proyecto)
        if form.is_valid():
            form.save()
            return render(request, 'formulario_proyecto.html', {"mensaje": "Proyecto editado con éxito"})
    else:
        form = ProyectoForm(instance=proyecto)

    return render(request, 'formulario_proyecto.html', {'form': form})

def eliminar_proyecto(request, nombre):
    proyecto = get_object_or_404(Proyecto, nombre=nombre)

    if request.method == 'POST':
        proyecto.delete()
        return redirect('AppElevator:lista_proyecto')
    
    return render(request, 'confirmar_eliminacion_proyecto.html', {'proyecto': proyecto})

# Editar Eliminar Autor y Html details
def autor_detalles(request, nombre):
    autor = Autor.objects.filter(nombre=nombre)
    print(autor)
    # if not autores.exists():
    #     return render(request, 'autor_no_encontrado.html', {'nombre': nombre})
    
    autorFound = autor.first()

    return render(request, 'autor_detalles.html', {'Autor': autorFound})

def editar_autor(request, nombre):
    autor = get_object_or_404(Autor, nombre=nombre)

    if request.method == 'POST':
        form = AutorForm(request.POST, instance=autor)
        if form.is_valid():
            form.save()
            return render(request, 'formulario_autores.html', {"mensaje": "Autor editado con éxito"})
    else:
        form = AutorForm(instance=autor)

    return render(request, 'formulario_autores.html', {'form': form})


def eliminar_autor(request, nombre):
    autor = get_object_or_404( Autor, nombre=nombre)

    if request.method == 'POST':
        autor.delete()
        return redirect('AppElevator:lista_autor')
    
    return render(request, 'confirmar_eliminacion_autor.html', {'autor': autor})

# Editar Eliminar Productor y Html details

def productor_detalles(request, nombre):
    productor = Productor.objects.filter(nombre=nombre)
    print(productor)
    # if not productor.exists():
    #     return render(request, 'productor_no_encontrado.html', {'nombre': nombre})
    
    autorFound = productor.first()

    return render(request, 'productor_detalles.html', {'Productor': autorFound})

def editar_productor(request, nombre):
    productor = get_object_or_404 (Productor, nombre=nombre)

    if request.method == 'POST':
        form = AutorForm(request.POST, instance=productor)
        if form.is_valid():
            form.save()
            return render(request, 'formulario_productores.html', {"mensaje": "Productor editado con éxito"})
    else:
        form = AutorForm(instance=productor)

    return render(request, 'formulario_productores.html', {'form': form})


def eliminar_productor(request, nombre):
    productor = get_object_or_404( Productor, nombre=nombre)

    if request.method == 'POST':
        productor.delete()
        return redirect('AppElevator:lista_productor')
    
    return render(request, 'confirmar_eliminacion_productor.html', {'productor': productor})


# Editar Eliminar Productora_audiovisual y Html details

def productora_detalles(request, nombre):
    productora = Productora_audiovisual.objects.filter(nombre=nombre)
    print(productora)
    # if not productora.exists():
    #     return render(request, 'productora_no_encontrado.html', {'nombre': nombre})
    
    autorFound = productora.first()

    return render(request, 'productora_detalles.html', {'Productora': autorFound})

def editar_productora(request, nombre):
    productora = get_object_or_404 (Productora_audiovisual, nombre=nombre)

    if request.method == 'POST':
        form = AutorForm(request.POST, instance=productora)
        if form.is_valid():
            form.save()
            return render(request, 'formulario_productoras.html', {"mensaje": "Productora editada con éxito"})
    else:
        form = AutorForm(instance=productora)

    return render(request, 'formulario_productoras.html', {'form': form})


def eliminar_productora(request, nombre):
    productora = get_object_or_404( Productora_audiovisual, nombre=nombre)

    if request.method == 'POST':
        productora.delete()
        return redirect('AppElevator:lista_productora')
    
    return render(request, 'confirmar_eliminacion_productora.html', {'productora': productora})

#login


def login_view(request):
    if request.method == 'POST':

AppElevator/templates/autor_detalles.html
{% extends 'page1.html' %}

{% block contenidoQueCambia %}
<div style="text-align: center;">
    <h1> Autor </h1>
    <div class="card-body" style="width: 50%; margin: 0 auto; border: 1px solid #000; padding: 20px; border-radius: 10px;">
        <h1 class="card-title">{{Autor.nombre}} {{Autor.apellido}}</h1> 
        <p class="card-text">Edad: {{Autor.edad}}</p>
        <p class="card-text">Lugar de nacimiento: {{Autor.pais}}</p>              
    </div>    
        <div>
             <a class="btn btn-warning" href="{% url 'AppElevator:editarAutor' Autor.nombre %}">Editar autor</a> 
             <a class="btn btn-danger" href="{% url 'AppElevator:eliminarAutor' Autor.nombre %}">Eliminar </a> 
           
        </div>
    </div>
{% endblock contenidoQueCambia %}

AppElevator/templates/confirmar_eliminacion_productora.html
<style>
    form {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
</style>

{% extends 'page1.html' %}

{% block contenidoQueCambia %}

  <h2>¿Estás seguro de que quieres eliminar el proyecto "{{ productora.id }}"?</h2>
  <form method="POST">
    {% csrf_token %}
    <button type="submit">Sí, eliminar</button>
  </form>
    <a href="{% url 'AppElevator:eliminarProductora' productora.id %}">Eliminar Productora</a>
  
{% endblock contenidoQueCambia %}

AppElevator/templates/editarPerfil.html
{% extends 'page1.html' %}

{% block contenidoQueCambia %}
    
    <form action="{% url 'EditarPerfil' %}" method="post">{% csrf_token %}

        {{miFomulario.as_p}}

        <button type="submit">Actualizar</button>
    </form>

{% endblock contenidoQueCambia %}

AppElevator/templates/formularioProductoras.html
<style>
    form {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
</style>

{% extends 'page1.html' %}

{% block contenidoQueCambia %}
<h1>Sección Formulario Productora Audiovisual</h1>
<form action="{% url 'AppElevator:formularioProductoras' %}" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar</button>
</form>



{% endblock contenidoQueCambia %}

AppElevator/templates/formularioProductores.html
<style>
    form {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
</style>

{% extends 'page1.html' %}

{% block contenidoQueCambia %}
<h1>Sección Formulario Productores</h1>
<form action="{% url 'AppElevator:formularioProductores' %}" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar</button>
</form>



{% endblock contenidoQueCambia %}

AppElevator/templates/listas_productor.html
{% extends 'page1.html' %}

{% block contenidoQueCambia %}
<h1>Sección Productores</h1>

<section class="listas_productor">
    {% for productor in listas_productor %}
    <div class="card" style="width: 18rem;">
      <img src="https://i.pinimg.com/originals/9e/4f/0d/9e4f0dd9e22b76d04e632618100dbb55.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{productor.nombre}} {{productor.apellido}}</h5> 
        <p class="card-text">País: {{productor.pais}}</p>

        <a href="/App-Elevator/productor-detalles/{{ productor.nombre }}/" class="btn btn-danger"> Ver perfil de : {{productor.nombre}} {{productor.apellido}}</a>
      </div>
    </div>
    {% endfor %}
</section>



<div class="d-flex justify-content-center">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if listas_productor.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ listas_productor.previous_page_number }}">Previous</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="?page={{ listas_productor.number }}">{{ listas_productor.number }}</a></li>
            {% if listas_productor.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ listas_productor.next_page_number }}">Next</a></li>
            {% endif %}
        </ul>
    </nav>
</div>

{% endblock contenidoQueCambia %}

AppElevator/templates/listas_productora.html
{% extends 'page1.html' %}

{% block contenidoQueCambia %}
<h1>Sección Productoras Audiovisuales</h1>

<section class="listas_productora">
    {% for productora in listas_productora %}
    <div class="card" style="width: 18rem;">
      <img src="https://i.pinimg.com/originals/9e/4f/0d/9e4f0dd9e22b76d04e632618100dbb55.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{productora.nombre}}</h5> 
        <p class="card-text">Página web: {{productora.pag_web}}</p>
        <p class="card-text">País: {{productora.pais}}</p>

        <a href="#" class="btn btn-danger"> Ingresar a : {{productora.nombre}}</a>
      </div>
    </div>
    {% endfor %}
</section>



<div class="d-flex justify-content-center">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if listas_productora.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ listas_productora.previous_page_number }}">Previous</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="?page={{ listas_productora.number }}">{{ listas_productora.number }}</a></li>
            {% if listas_productora.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ listas_productora.next_page_number }}">Next</a></li>
            {% endif %}
        </ul>
    </nav>
</div>

{% endblock contenidoQueCambia %}

AppElevator/templates/listas_proyecto.html
    {% extends 'page1.html' %}

{% block contenidoQueCambia %}
<h1>Sección Proyectos</h1>

<section class="listas_proyecto">
    {% for proyecto in listas_proyecto %}
    <div class="card" style="width: 18rem;">
      <img src="https://i.pinimg.com/originals/9e/4f/0d/9e4f0dd9e22b76d04e632618100dbb55.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{proyecto.nombre}}</h5> 
        <p class="card-text">{{proyecto.logline}}</p>
        <p class="card-text">{{proyecto.genero}}</p>

                      
        <a href="/App-Elevator/proyecto-detalles/{{ proyecto.nombre }}/" class="btn btn-danger">Ingresar a : {{ proyecto.nombre }}</a>
    </div>
    </div>
    {% endfor %}
</section>

<div class="d-flex justify-content-center">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if listas_proyecto.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ listas_proyecto.previous_page_number }}">Previous</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="?page={{ listas_proyecto.number }}">{{ listas_proyecto.number }}</a></li>
            {% if listas_proyecto.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ listas_proyecto.next_page_number }}">Next</a></li>
            {% endif %}
        </ul>
    </nav>
</div>

{% endblock contenidoQueCambia %}

AppElevator/templates/login.html
{% extends 'page1.html' %}

{% block contenidoQueCambia %}
    <h1>Página de Inicio</h1>


    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Iniciar Sesión</button>
    </form>
  

{% endblock contenidoQueCambia %}

AppElevator/templates/productor_detalles.html
{% extends 'page1.html' %}

{% block contenidoQueCambia %}
<div style="text-align: center;">
    <h1>Productor</h1>
    <div class="card-body" style="width: 50%; margin: 0 auto; border: 1px solid #000; padding: 20px; border-radius: 10px;">
        <h1 class="card-title">{{Productor.nombre}} {{Productor.apellido}}</h1> 
        <p class="card-text">Web: {{Productor.pag_web}}</p>
        <p class="card-text">Lugar de nacimiento: {{Productor.pais}}</p>              
    </div>    
        <div>
             <a class="btn btn-warning" href="{% url 'AppElevator:editarProductor' Productor.nombre %}">Editar Productor</a> 
             <a class="btn btn-danger" href="{% url 'AppElevator:eliminarProductor' Productor.nombre %}">Eliminar </a> 
           
        </div>
    </div>
{% endblock contenidoQueCambia %}

AppElevator/templates/proyecto_detalles.html
{% extends 'page1.html' %}

{% block contenidoQueCambia %}
<div style="text-align: center;">
    <h1>Proyecto </h1>
    <div class="card-body" style="width: 50%; margin: 0 auto; border: 1px solid #000; padding: 20px; border-radius: 10px;">
        <h1 class="card-title">{{proyecto.nombre}}</h1> 
        <p class="card-text">{{proyecto.logline}}</p>
        <p class="card-text">{{proyecto.plot}}</p>
        <p class="card-text">{{proyecto.genero}}</p>              
    </div>

    <!-- menu Crear Editar Borrar -->
    
        </button>
        <div>
            <a class="btn btn-danger" href="{% url 'AppElevator:formularioProyecto' %}">Nuevo Proyecto</a>
            <a class="btn btn-warning" href="{% url 'AppElevator:editarProyecto' proyecto.nombre %}">Editar Proyecto</a>
            <a class="btn btn-danger" href="{% url 'AppElevator:eliminarProyecto' proyecto.nombre %}">Eliminar Proyecto</a>
           
        </div>
    </div>
{% endblock contenidoQueCambia %}

AppElevator/templates/submit.html
<form class="form-subscribe" id="contactForm" data-sb-form-api-token="API_TOKEN">
    <!-- Email address input-->
    <div class="row">
        <div class="col">
            <input class="form-control form-control-lg" id="emailAddress" type="email" placeholder="Email Address" data-sb-validations="required,email" />
            <div class="invalid-feedback text-white" data-sb-feedback="emailAddress:required">Email Address is required.</div>
            <div class="invalid-feedback text-white" data-sb-feedback="emailAddress:email">Email Address Email is not valid.</div>
        </div>
        <div class="col-auto"><button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Submit</button></div>
    </div>
    <!-- Submit success message-->
    <!---->
    <!-- This is what your users will see when the form-->
    <!-- has successfully submitted-->
    <div class="d-none" id="submitSuccessMessage">
        <div class="text-center mb-3">
            <div class="fw-bolder">Form submission successful!</div>
            <p>To activate this form, sign up at</p>
            <a class="text-white" href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
        </div>